sonar.projectKey=crisisview-frontend
sonar.projectName=CrisisView Frontend
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=app/**/*.test.ts,app/**/*.test.tsx
sonar.exclusions=node_modules/**,.next/**,out/**,build/**,public/**,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,app/layout.tsx,app/page.tsx,app/components/Map.tsx,app/admin/**/*
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
