sonar.projectKey=crisisview-api
sonar.projectName=CrisisView API
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,__tests__/**,jest.config.js,babel.config.js,seed.js,migration.js
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
